import { getStrings } from "./localization/Localization";
import { createTheme, ITheme } from "@fluentui/react/lib/Styling";

export enum ThemeTypes {
  Light,
  Dark,
}

/** All existing themes. The theme dropdown menu populates items in the given order, so don't change it. */
export enum Themes {
  Default = 0,
  EarthAndSky = 1,
  ContrastLight = 2,
  Muted = 3,
  Slate = 4,
  DeepSea = 5,
  Midnight = 6,
  ContrastDark = 7,
  Dim = 8,
}

export interface ISupportedTheme {
  localizedName: string;
  theme: ITheme;
  themeId: Themes;
  themeType: ThemeTypes;
}

const strings = getStrings();

/** Colors with associated themes. Note: items here are displayed in the order given below for the themes dropdown. */
export const themes: { [key in Themes]: ISupportedTheme } = {
  [Themes.ContrastDark]: {
    localizedName: strings.ThemeContrastDark,
    themeId: Themes.ContrastDark,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#ffea00",
        themeLighterAlt: "#0a0900",
        themeLighter: "#292500",
        themeLight: "#4d4600",
        themeTertiary: "#998c00",
        themeSecondary: "#e0ce00",
        themeDarkAlt: "#ffec19",
        themeDark: "#ffef3d",
        themeDarker: "#fff370",
        neutralLighterAlt: "#0b0b0b",
        neutralLighter: "#151515",
        neutralLight: "#252525",
        neutralQuaternaryAlt: "#2f2f2f",
        neutralQuaternary: "#373737",
        neutralTertiaryAlt: "#595959",
        neutralTertiary: "#c8c8c8",
        neutralSecondary: "#d0d0d0",
        neutralPrimaryAlt: "#dadada",
        neutralPrimary: "#ffffff",
        neutralDark: "#f4f4f4",
        black: "#f8f8f8",
        white: "#000000",
      },
    }),
  },
  [Themes.ContrastLight]: {
    localizedName: strings.ThemeContrastLight,
    themeId: Themes.ContrastLight,
    themeType: ThemeTypes.Light,
    theme: createTheme({
      palette: {
        themePrimary: "#000080",
        themeLighterAlt: "#f0f0fa",
        themeLighter: "#c5c5eb",
        themeLight: "#9898d9",
        themeTertiary: "#4747b3",
        themeSecondary: "#11118f",
        themeDarkAlt: "#000073",
        themeDark: "#000061",
        themeDarker: "#000047",
        neutralLighterAlt: "#f8f8f8",
        neutralLighter: "#f4f4f4",
        neutralLight: "#eaeaea",
        neutralQuaternaryAlt: "#dadada",
        neutralQuaternary: "#d0d0d0",
        neutralTertiaryAlt: "#c8c8c8",
        neutralTertiary: "#595754",
        neutralSecondary: "#373534",
        neutralPrimaryAlt: "#2f2d2c",
        neutralPrimary: "#000000",
        neutralDark: "#151413",
        black: "#0b0b0a",
        white: "#ffffff",
      },
    }),
  },
  [Themes.DeepSea]: {
    localizedName: strings.ThemeDeepSea,
    themeId: Themes.DeepSea,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#e8a63c",
        themeLighterAlt: "#090702",
        themeLighter: "#251b0a",
        themeLight: "#463212",
        themeTertiary: "#8b6424",
        themeSecondary: "#cc9235",
        themeDarkAlt: "#eaaf4e",
        themeDark: "#eeba68",
        themeDarker: "#f2cc8e",
        neutralLighterAlt: "#02132b",
        neutralLighter: "#041833",
        neutralLight: "#092141",
        neutralQuaternaryAlt: "#0e274a",
        neutralQuaternary: "#122c51",
        neutralTertiaryAlt: "#27456f",
        neutralTertiary: "#e8f6f6",
        neutralSecondary: "#ebf8f7",
        neutralPrimaryAlt: "#eff9f9",
        neutralPrimary: "#dcf2f1",
        neutralDark: "#f7fcfc",
        black: "#fbfdfd",
        white: "#000e21",
      },
    }),
  },
  [Themes.Default]: {
    localizedName: strings.ThemeDefault,
    themeId: Themes.Default,
    themeType: ThemeTypes.Light,
    theme: createTheme({
      palette: {
        themePrimary: "#5f609e",
        themeLighterAlt: "#f7f7fb",
        themeLighter: "#e0e0ef",
        themeLight: "#c7c7e2",
        themeTertiary: "#9696c5",
        themeSecondary: "#6e6faa",
        themeDarkAlt: "#55568e",
        themeDark: "#484978",
        themeDarker: "#353659",
        neutralLighterAlt: "#e4e4e4",
        neutralLighter: "#e1e1e1",
        neutralLight: "#d7d7d7",
        neutralQuaternaryAlt: "#c9c9c9",
        neutralQuaternary: "#bfbfbf",
        neutralTertiaryAlt: "#b8b8b8",
        neutralTertiary: "#595959",
        neutralSecondary: "#373737",
        neutralPrimaryAlt: "#2f2f2f",
        neutralPrimary: "#000000",
        neutralDark: "#151515",
        black: "#0b0b0b",
        white: "#ebebeb",
      },
    }),
  },
  [Themes.Dim]: {
    localizedName: strings.ThemeDim,
    themeId: Themes.Dim,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#784600",
        themeLighterAlt: "#050300",
        themeLighter: "#130b00",
        themeLight: "#241500",
        themeTertiary: "#482a00",
        themeSecondary: "#693e00",
        themeDarkAlt: "#85530d",
        themeDark: "#986825",
        themeDarker: "#b3894f",
        neutralLighterAlt: "#000b01",
        neutralLighter: "#021502",
        neutralLight: "#052506",
        neutralQuaternaryAlt: "#092f0a",
        neutralQuaternary: "#0c370d",
        neutralTertiaryAlt: "#1f5921",
        neutralTertiary: "#222222",
        neutralSecondary: "#454443",
        neutralPrimaryAlt: "#656463",
        neutralPrimary: "#737270",
        neutralDark: "#949392",
        black: "#b0afae",
        white: "#000000",
      },
    }),
  },
  [Themes.EarthAndSky]: {
    localizedName: strings.ThemeEarthAndSky,
    themeId: Themes.EarthAndSky,
    themeType: ThemeTypes.Light,
    theme: createTheme({
      palette: {
        themePrimary: "#8f4700",
        themeLighterAlt: "#fbf6f0",
        themeLighter: "#eddac7",
        themeLight: "#ddbc9b",
        themeTertiary: "#bc834b",
        themeSecondary: "#9c5813",
        themeDarkAlt: "#814000",
        themeDark: "#6d3600",
        themeDarker: "#502800",
        neutralLighterAlt: "#e9f6f8",
        neutralLighter: "#e5f2f4",
        neutralLight: "#dce8ea",
        neutralQuaternaryAlt: "#cdd8da",
        neutralQuaternary: "#c4cfd0",
        neutralTertiaryAlt: "#bcc7c8",
        neutralTertiary: "#a19f9d",
        neutralSecondary: "#605e5c",
        neutralPrimaryAlt: "#3b3a39",
        neutralPrimary: "#323130",
        neutralDark: "#201f1e",
        black: "#000000",
        white: "#f0fdff",
      },
    }),
  },
  [Themes.Midnight]: {
    localizedName: strings.ThemeMidnight,
    themeId: Themes.Midnight,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#d1ad7d",
        themeLighterAlt: "#080705",
        themeLighter: "#211c14",
        themeLight: "#3f3426",
        themeTertiary: "#7d684b",
        themeSecondary: "#b8986e",
        themeDarkAlt: "#d6b489",
        themeDark: "#dcbf99",
        themeDarker: "#e5cfb2",
        neutralLighterAlt: "#0b0b0b",
        neutralLighter: "#151515",
        neutralLight: "#252525",
        neutralQuaternaryAlt: "#2f2f2f",
        neutralQuaternary: "#373737",
        neutralTertiaryAlt: "#595959",
        neutralTertiary: "#e0e0e0",
        neutralSecondary: "#e5e5e5",
        neutralPrimaryAlt: "#eaeaea",
        neutralPrimary: "#d1d1d1",
        neutralDark: "#f4f4f4",
        black: "#f9f9f9",
        white: "#000000",
      },
    }),
  },
  [Themes.Muted]: {
    localizedName: strings.ThemeMuted,
    themeId: Themes.Muted,
    themeType: ThemeTypes.Light,
    theme: createTheme({
      palette: {
        themePrimary: "#23295c",
        themeLighterAlt: "#f2f3f8",
        themeLighter: "#ced0e5",
        themeLight: "#a8acce",
        themeTertiary: "#63689d",
        themeSecondary: "#33396f",
        themeDarkAlt: "#1f2553",
        themeDark: "#1b1f46",
        themeDarker: "#141733",
        neutralLighterAlt: "#bdbdbb",
        neutralLighter: "#bfc0be",
        neutralLight: "#c4c4c2",
        neutralQuaternaryAlt: "#c6c7c5",
        neutralQuaternary: "#c9c9c7",
        neutralTertiaryAlt: "#d2d2d1",
        neutralTertiary: "#595959",
        neutralSecondary: "#373737",
        neutralPrimaryAlt: "#2f2f2f",
        neutralPrimary: "#000000",
        neutralDark: "#151515",
        black: "#0b0b0b",
        white: "#babab8",
      },
    }),
  },
  [Themes.Slate]: {
    localizedName: strings.ThemeSlate,
    themeId: Themes.Slate,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#9798bd",
        themeLighterAlt: "#060608",
        themeLighter: "#18181e",
        themeLight: "#2d2e39",
        themeTertiary: "#5b5b71",
        themeSecondary: "#8586a6",
        themeDarkAlt: "#a0a1c3",
        themeDark: "#aeafcd",
        themeDarker: "#c1c2da",
        neutralLighterAlt: "#303736",
        neutralLighter: "#373f3e",
        neutralLight: "#434c4b",
        neutralQuaternaryAlt: "#4b5453",
        neutralQuaternary: "#515b5a",
        neutralTertiaryAlt: "#6c7775",
        neutralTertiary: "#dfdfdf",
        neutralSecondary: "#e4e4e4",
        neutralPrimaryAlt: "#e9e9e9",
        neutralPrimary: "#cfcfcf",
        neutralDark: "#f4f4f4",
        black: "#f9f9f9",
        white: "#272e2d",
      },
    }),
  },
};
